"""add rol to usuarios

Revision ID: cd5ae23308a2
Revises: d2301ff53f1f
Create Date: 2026-04-27 11:47:09.762993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd5ae23308a2'
down_revision = 'd2301ff53f1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'rol',
                sa.String(length=20),
                nullable=False,
                server_default='cliente',
            )
        )
        batch_op.create_index(batch_op.f('ix_usuarios_rol'), ['rol'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_rol'))
        batch_op.drop_column('rol')

    # ### end Alembic commands ###
